### PR TITLE
fix: generate member accessors for referenced collection element members in Quarkus

### LINKED ISSUE #1580: Exception with DSV and Quarkus
[ERROR] 	[error]: Build step ai.timefold.solver.quarkus.deployment.TimefoldProcessor#recordAndRegisterBuildTimeBeans threw an exception: java.lang.IllegalArgumentException: The source path (dependencySet[].processingEnd) starting from root class (Job) references a member (processingEnd) on class (List) that does not exist.

@larsbeck has more.

### PR DESCRIPTION
**Pull request by Christopher-Chianelli**
Fixes #1580

### CODE REVIEW

File: quarkus-integration/quarkus/deployment/src/main/java/ai/timefold/solver/quarkus/deployment/TimefoldProcessor.java [hunk 1]
```diff
@@ -1096,21 +1096,47 @@ private static void generateDomainAccessorsForShadowSources(IndexView indexView,
             var sources = shadowSources.value().asStringArray();
             for (var source : sources) {
                 var currentType = rootType;
+                java.lang.reflect.Type currentGenericType = rootType;
                 var parts = source.split(RootVariableSource.MEMBER_SEPERATOR_REGEX);
+                boolean isAfterCollection = false;
```
Comment (triceo) [inline quarkus-integration/quarkus/deployment/src/main/java/ai/timefold/solver/quarkus/deployment/TimefoldProcessor.java:1101]: Definitely `var`, as in the rest of the file.

File: quarkus-integration/quarkus/deployment/src/main/java/ai/timefold/solver/quarkus/deployment/TimefoldProcessor.java [hunk 2]
```diff
@@ -1096,21 +1096,47 @@ private static void generateDomainAccessorsForShadowSources(IndexView indexView,
...
+                String collectionName = "";
                 for (var part : parts) {
-                    var memberName = part.endsWith(RootVariableSource.COLLECTION_REFERENCE_SUFFIX)
+                    var isCollection = part.endsWith(RootVariableSource.COLLECTION_REFERENCE_SUFFIX);
```
Comment (triceo) [inline quarkus-integration/quarkus/deployment/src/main/java/ai/timefold/solver/quarkus/deployment/TimefoldProcessor.java:1104]: Do we have the path parsing code separately in Core and in Quarkus?
Preferrably, we'd reuse the parsing logic from Solver.

File: quarkus-integration/quarkus/deployment/src/test/java/ai/timefold/solver/quarkus/TimefoldProcessorSupplierShadowSolutionSimpleSolveTest.java [hunk 3]
```diff
@@ -10,9 +10,9 @@
 import jakarta.inject.Inject;
 
 import ai.timefold.solver.core.api.solver.SolverManager;
-import ai.timefold.solver.quarkus.testdomain.suppliervariable.constraints.TestdataQuarkusSupplierVariableConstraintProvider;
-import ai.timefold.solver.quarkus.testdomain.suppliervariable.domain.TestdataQuarkusSupplierVariableEntity;
-import ai.timefold.solver.quarkus.testdomain.suppliervariable.domain.TestdataQuarkusSupplierVariableSolution;
+import ai.timefold.solver.quarkus.testdomain.suppliervariable.simple.constraints.TestdataQuarkusSupplierVariableSimpleConstraintProvider;
+import ai.timefold.solver.quarkus.testdomain.suppliervariable.simple.domain.TestdataQuarkusSupplierVariableSimpleEntity;
+import ai.timefold.solver.quarkus.testdomain.suppliervariable.simple.domain.TestdataQuarkusSupplierVariableSimpleSolution;
```
Comment (triceo) [inline quarkus-integration/quarkus/deployment/src/test/java/ai/timefold/solver/quarkus/TimefoldProcessorSupplierShadowSolutionSimpleSolveTest.java:15]: Considering that the FQN is already very long, do we need to repeat the `domain` there?

**Review by triceo — COMMENTED** [review]
Requesting some changes.
Also - are we sure this is not an issue in Spring as well?
Finally - if we're touching the path detection code, this may be related as well:

https://timefold.slack.com/archives/C04PQNRTJVD/p1747634074682339

File: quarkus-integration/quarkus/deployment/src/main/java/ai/timefold/solver/quarkus/deployment/TimefoldProcessor.java [hunk 4]
```diff
@@ -1096,21 +1096,47 @@ private static void generateDomainAccessorsForShadowSources(IndexView indexView,
             var sources = shadowSources.value().asStringArray();
             for (var source : sources) {
                 var currentType = rootType;
+                java.lang.reflect.Type currentGenericType = rootType;
```
[the remark this answers is not in the document]
Comment (Christopher-Chianelli) [reply quarkus-integration/quarkus/deployment/src/main/java/ai/timefold/solver/quarkus/deployment/TimefoldProcessor.java:1099]: Cannot use FQN, since jboss Type already imported. Cannot use var, since var infers `Class` when we want `Type`.

File: quarkus-integration/quarkus/deployment/src/test/java/ai/timefold/solver/quarkus/TimefoldProcessorSupplierShadowSolutionSimpleSolveTest.java (hunk 3 above)
Comment (Christopher-Chianelli) [reply quarkus-integration/quarkus/deployment/src/test/java/ai/timefold/solver/quarkus/TimefoldProcessorSupplierShadowSolutionSimpleSolveTest.java:15]: That how all the other `testdomain` classes does it.

Comment (triceo) [reply quarkus-integration/quarkus/deployment/src/test/java/ai/timefold/solver/quarkus/TimefoldProcessorSupplierShadowSolutionSimpleSolveTest.java:15]: Not anymore. :-) We changed it in `core`, we shortened the FQNs significantly.
(They started giving trouble on Windows, long paths.)

**Comment by Christopher-Chianelli** [comment]
@triceo Spring is not affected; the reason why Quarkus has it own parsing logic is to generate member accessors ahead of time which is needed for native image.

**Review by triceo — APPROVED** [review]
