### PR TITLE
feat: fail-fast if shadow variables has a fixed loop in their graph

### LINKED ISSUE #1675: Feat: Fail fast if DSV sources force a loop
If a declarative shadow variable is sourced in a way that it inevitably ends up pointing back to itself, fail fast. Clearly document that.

Loops are a failure state; models should not be designed with intentionally induced loops.
The fail fast should identify and print at least one loop, if not all of them.

### PR DESCRIPTION
**Pull request by Christopher-Chianelli**
Closes https://github.com/TimefoldAI/timefold-solver/issues/1675

### CODE REVIEW

File: core/src/main/java/ai/timefold/solver/core/impl/domain/variable/declarative/DefaultTopologicalOrderGraph.java [hunk 1]
```diff
@@ -39,6 +39,25 @@ List<Integer> getComponent(int node) {
         return componentMap.get(node);
     }
 
+    List<List<Integer>> getLoopedComponentList() {
+        var out = new ArrayList<List<Integer>>();
```
Comment (triceo) [inline core/src/main/java/ai/timefold/solver/core/impl/domain/variable/declarative/DefaultTopologicalOrderGraph.java]: This can be sized by `componentMap.size()`. For large graphs, this will save quite a few reallocations, even though occasionally it may overshoot.

File: core/src/main/java/ai/timefold/solver/core/impl/domain/variable/declarative/DefaultTopologicalOrderGraph.java [hunk 2]
```diff
@@ -39,6 +39,25 @@ List<Integer> getComponent(int node) {
...
+        var visited = new HashSet<Integer>();
```
Comment (triceo) [inline core/src/main/java/ai/timefold/solver/core/impl/domain/variable/declarative/DefaultTopologicalOrderGraph.java]: I wonder if `BitSet` wouldn't be more suitable for this and the previous `List<Integer>`. It will avoid boxing, and `addAll` will become a bitwise operation.

I understand all of this only happens once, but considering the sizes of the graphs we know we'll get, cold start performance is also important.

File: core/src/main/java/ai/timefold/solver/core/impl/domain/variable/declarative/VariableReferenceGraphBuilder.java [hunk 3]
```diff
@@ -129,4 +135,94 @@ public VariableReferenceGraph build(IntFunction<TopologicalOrderGraph> graphCrea
         return out;
     }
 
+    private void assertNoFixedLoops() {
+        var graph = new DefaultTopologicalOrderGraph(nodeList.size());
```
Comment (triceo) [inline core/src/main/java/ai/timefold/solver/core/impl/domain/variable/declarative/VariableReferenceGraphBuilder.java:139]: This graph is used as a throw-away implementation purely for the purposes of loop detection. If my memory serves, there is more than one place in the code where this happens (where "this" is using the one-time graph). I wonder if this should be documented in Javadoc as one of the purposes of the `Default...Graph`.

File: core/src/main/java/ai/timefold/solver/core/impl/domain/variable/declarative/VariableReferenceGraphBuilder.java [hunk 4]
```diff
@@ -129,4 +135,94 @@ public VariableReferenceGraph build(IntFunction<TopologicalOrderGraph> graphCrea
...
+            for (var toNode : fixedEdge.getValue()) {
+                var toNodeId = toNode.graphNodeId();
+                graph.addEdge(fromNodeId, toNodeId);
+            }
+        }
+
+        var changedBitSet = new BitSet();
+        graph.commitChanges(changedBitSet);
+
+        if (changedBitSet.cardinality() != 0) {
```
Comment (triceo) [inline core/src/main/java/ai/timefold/solver/core/impl/domain/variable/declarative/VariableReferenceGraphBuilder.java]: I'd invert the condition and return.
The rest of the code can be un-nested, and the reader has one less condition to think about which applies to the block.

File: core/src/main/java/ai/timefold/solver/core/impl/domain/variable/declarative/VariableReferenceGraphBuilder.java [hunk 5]
```diff
@@ -129,4 +135,94 @@ public VariableReferenceGraph build(IntFunction<TopologicalOrderGraph> graphCrea
...
+            // At least one node's loop status has changed,
+            // and since the empty graph has no loops, that
+            // mean there is at least one fixed loop in the graph.
+            var loopedComponents = graph.getLoopedComponentList();
+            var limit = 3;
+            var isLimited = loopedComponents.size() > limit;
+            var loopedVariables = new LinkedHashSet<VariableMetaModel<?, ?, ?>>();
```
Comment (triceo) [inline core/src/main/java/ai/timefold/solver/core/impl/domain/variable/declarative/VariableReferenceGraphBuilder.java]: Since variable count is typically a low, fixed number, I wonder if the subsequent loop couldn't be made more efficient knowing that.

Although since `loopedComponents` is possibly large, it's probably the right call to iterate over it just once.

File: core/src/main/java/ai/timefold/solver/core/impl/domain/variable/declarative/VariableReferenceGraphBuilder.java [hunk 6]
```diff
@@ -129,4 +135,94 @@ public VariableReferenceGraph build(IntFunction<TopologicalOrderGraph> graphCrea
...
+                                        .forEach(loopedVariables::add));
+            }
+
+            var out = new StringBuilder("There are fixed dependency loops in the graph for variables %s:%n"
+                    .formatted(loopedVariables));
+            for (var i = 0; i < Math.min(loopedComponents.size(), limit); i++) {
+                out.append(
+                        loopedComponents.get(i)
+                                .stream()
+                                .map(nodeList::get)
```
Comment (triceo) [inline core/src/main/java/ai/timefold/solver/core/impl/domain/variable/declarative/VariableReferenceGraphBuilder.java]: The conversion of `loopedComponent` to a stream of nodes is happening twice - first on line 161, second here. Arguably we can cache this computation on line 161 and reuse it here.

File: core/src/main/java/ai/timefold/solver/core/impl/domain/variable/declarative/VariableReferenceGraphBuilder.java [hunk 7]
```diff
@@ -129,4 +135,94 @@ public VariableReferenceGraph build(IntFunction<TopologicalOrderGraph> graphCrea
...
+                                .map(GraphNode::toString)
+                                .collect(Collectors.joining(", ",
+                                        "- [",
+                                        "]\n")));
```
Comment (triceo) [inline core/src/main/java/ai/timefold/solver/core/impl/domain/variable/declarative/VariableReferenceGraphBuilder.java]: Let's replace "\n" with the line separator constant.

File: core/src/main/java/ai/timefold/solver/core/impl/domain/variable/declarative/VariableReferenceGraphBuilder.java [hunk 8]
```diff
@@ -129,4 +135,94 @@ public VariableReferenceGraph build(IntFunction<TopologicalOrderGraph> graphCrea
...
+            }
+            if (isLimited) {
+                out.append("- ...(");
+                out.append(loopedComponents.size() - limit);
+                out.append(" more)\n");
```
Comment (triceo) [inline core/src/main/java/ai/timefold/solver/core/impl/domain/variable/declarative/VariableReferenceGraphBuilder.java]: Dtto.

File: core/src/main/java/ai/timefold/solver/core/impl/domain/variable/declarative/VariableReferenceGraphBuilder.java [hunk 9]
```diff
@@ -129,4 +135,94 @@ public VariableReferenceGraph build(IntFunction<TopologicalOrderGraph> graphCrea
...
+            }
+            out.append("""
+
+                    Fixed dependency loops indicate a problem in either the input problem or in the @%s of the looped @%s.
+                    If a downstream variable depends on an upstream variable, the upstream variable cannot depend on the
+                    downstream variable on the same entity. As such, a model that looks like this is invalid:
```
Comment (triceo) [inline core/src/main/java/ai/timefold/solver/core/impl/domain/variable/declarative/VariableReferenceGraphBuilder.java]: For these long sentences, line breaks after each will help readability.

File: core/src/main/java/ai/timefold/solver/core/impl/domain/variable/declarative/VariableReferenceGraphBuilder.java [hunk 10]
```diff
@@ -129,4 +135,94 @@ public VariableReferenceGraph build(IntFunction<TopologicalOrderGraph> graphCrea
...
+                    entity1:variable1 (source)-> entity1:variable2 (source)-> entity1:variable1
+                    In code, this situation looks like this:
+
+                        @ShadowSources("variable2")
+                        String variable1Supplier() { /* ... */ }
+
+                        @ShadowSources("variable1")
+                        String variable2Supplier() { /* ... */ }
+
+                    This applies even if the upstream variable is reached indirectly:
```
Comment (triceo) [inline core/src/main/java/ai/timefold/solver/core/impl/domain/variable/declarative/VariableReferenceGraphBuilder.java]: "indirectly" -> "transitively"?

File: core/src/main/java/ai/timefold/solver/core/impl/domain/variable/declarative/VariableReferenceGraphBuilder.java [hunk 11]
```diff
@@ -129,4 +135,94 @@ public VariableReferenceGraph build(IntFunction<TopologicalOrderGraph> graphCrea
...
+                            @ShadowSources("fact.variable1")
+                            String variable1Supplier() { /* ... */ }
+                            // ...
+                        }
+
+                        Entity a = new Entity();
+                        Entity b = new Entity();
+                        a.setFact(b);
+                        b.setFact(a);
+                        // a depends on b, and b depends on a, which is invalid.
```
Comment (triceo) [inline core/src/main/java/ai/timefold/solver/core/impl/domain/variable/declarative/VariableReferenceGraphBuilder.java]: Isn't this a runtime loop? The dependency only happens at runtime, based on the data set. I thought that these "runtime" loops are different from the "fixed" loops, and runtime loops would be allowed. We handle them at runtime with the @ShadowVariablesInconsitent, therefore there should be no fail-fast here.

What am I missing? What is the difference here?

Also: Having an `Entity` be called `fact` is kinda confusing. Maybe a better name for the variable?

**Review by triceo — COMMENTED** [review]
Some questions, some suggestions for improvement.
Love the specificity of the error message!

I wonder if we should have language for the "fixed loops" and "runtime loops", and encode that language in user-facing documentation. We will often speak about this with users in Discussions etc., we should probably formalize the terminology.

File: core/src/main/java/ai/timefold/solver/core/impl/domain/variable/declarative/VariableReferenceGraphBuilder.java (hunk 11 above)
Comment (Christopher-Chianelli) [reply core/src/main/java/ai/timefold/solver/core/impl/domain/variable/declarative/VariableReferenceGraphBuilder.java]: It a fixed runtime loop; that fact is a fact on the entity, NOT a planning variable. PlanningEntities can be used as facts on another PlanningEntity.

```java
@PlanningEntity
class Task {
    List<Task> dependencies;  // this is a fact; the solver cannot change this

    @ShadowVariable(supplierName="startTimeSupplier")
     LocalDateTime startTime;
     
     //...
     @ShadowSources("dependencies[].startTime")
      public LocalDateTime startTimeSupplier() { /* ... */}
}

var taskA = new Task();
var taskB = new Task();

// The solver cannot ever break this loop, since it is caused by facts on the entities
taskA.setDependencies(List.of(taskB));
taskB.setDependencies(List.of(taskA));
```

Comment (Christopher-Chianelli) [reply core/src/main/java/ai/timefold/solver/core/impl/domain/variable/declarative/VariableReferenceGraphBuilder.java]: Then there is dynamic runtime loops, when a variable (that the solver can change) causes the loop:

```java
@PlanningEntity
class Task {
    List<Task> dependencies;
    @PreviousElementShadowVariable
    Task previous;

    @ShadowVariable(supplierName="startTimeSupplier")
     LocalDateTime startTime;
     
     //...
     @ShadowSources({"previous.startTime", "dependencies[].startTime"})
      public LocalDateTime startTimeSupplier() { /* ... */}
}

var taskA = new Task();
var taskB = new Task();

// The solver can break this loop by moving taskA after taskB
taskB.setDependencies(List.of(taskA));
taskA.setPrevious(taskB);
```

Comment (triceo) [reply core/src/main/java/ai/timefold/solver/core/impl/domain/variable/declarative/VariableReferenceGraphBuilder.java]: Interesting. So we have three kinds of loops:

1. Fixed loops.
2. Runtime loops.
3. Fixed+runtime loops.

This tells me that "runtime" is a wrong name for 2 and 3, because both of them happen at runtime. That probably also means "fixed" is a wrong name, because 1 and 3 are both fixed. Ideally, all three would have distinct names.

What we need:
- Naming. (Suggestions?)
- A section for this in the docs, listing the types and what happens with each.

Comment (triceo) [reply core/src/main/java/ai/timefold/solver/core/impl/domain/variable/declarative/VariableReferenceGraphBuilder.java]: Thinking out loud:

1. Forced loop. (Source _declaration_ forces the loop.)
2. Dynamic loop. (Data creates the loop.)
3. Implied loop. (Source _type_ implies the loop.)

File: core/src/main/java/ai/timefold/solver/core/impl/domain/variable/declarative/DefaultTopologicalOrderGraph.java (hunk 2 above)
Comment (Christopher-Chianelli) [reply core/src/main/java/ai/timefold/solver/core/impl/domain/variable/declarative/DefaultTopologicalOrderGraph.java]: Note: most of the time, this is never called. This is only called if there are fixed loops in the input.

File: core/src/main/java/ai/timefold/solver/core/impl/domain/variable/declarative/VariableReferenceGraphBuilder.java (hunk 11 above)
Comment (Christopher-Chianelli) [reply core/src/main/java/ai/timefold/solver/core/impl/domain/variable/declarative/VariableReferenceGraphBuilder.java]: Source-induced, fact-induced, variable-induced?

Comment (triceo) [reply core/src/main/java/ai/timefold/solver/core/impl/domain/variable/declarative/VariableReferenceGraphBuilder.java]: Could be.

File: core/src/main/java/ai/timefold/solver/core/impl/domain/variable/declarative/VariableReferenceGraphBuilder.java (hunk 3 above)
Comment (Christopher-Chianelli) [reply core/src/main/java/ai/timefold/solver/core/impl/domain/variable/declarative/VariableReferenceGraphBuilder.java:139]: TBH, any implementation of `TopologicalOrderGraph` can be used; there isn't anything special about `DefaultTopologicalOrderGraph` beside the fact it is always available.

**Review by triceo — APPROVED** [review]
LGTM. 

Will merge when the new loop terminology makes it to the docs with examples, and when the source code is updated to reflect the terminology.

**Review by triceo — APPROVED** [review]
