### PR TITLE
fix: do not fail-fast when multiple setters with the same name exists

### LINKED ISSUE #2165: Overloaded setters not allowed on planning entity in Solver 2.0
Consider a planning entity `SolverStop` with the following property and two setters:
```
    private MultipleTimeWindow multipleTimeWindow;

    public void setMultipleTimeWindow(MultipleTimeWindow multipleTimeWindow) {
        this.multipleTimeWindow =
                multipleTimeWindow == null ? new MultipleTimeWindow() : multipleTimeWindow;
    }

    public void setMultipleTimeWindow(List<TimeWindow> timeWindows) {
        this.multipleTimeWindow = new MultipleTimeWindow(timeWindows);
    }
```

Solver fails to generate a solution cloner with the following exception:

```
[ERROR] Caused by: java.lang.IllegalStateException: The containingClass (class ai.timefold.model.pickupdeliveryrouting.solver.domain.SolverStop) has multiple setter methods ([public void ai.timefold.model.pickupdeliveryrouting.solver.domain.SolverStop.setMultipleTimeWindow(ai.timefold.model.pickupdeliveryrouting.solver.domain.MultipleTimeWindow), public void ai.timefold.model.pickupdeliveryrouting.solver.domain.SolverStop.setMultipleTimeWindow(java.util.List)]) with the propertyName (multipleTimeWindow).                                                                                                           
[ERROR]         at ai.timefold.solver.core.impl.domain.common.ReflectionHelper.getSetterMethod(ReflectionHelper.java:263)
[ERROR]         at ai.timefold.solver.core.impl.domain.common.accessor.gizmo.GizmoFieldHandler.<init>(GizmoFieldHandler.java:30)
[ERROR]         at ai.timefold.solver.core.impl.domain.common.accessor.gizmo.GizmoMemberHandler.of(GizmoMemberHandler.java:32)
[ERROR]         at ai.timefold.solver.core.impl.domain.common.accessor.gizmo.GizmoMemberDescriptor.<init>(GizmoMemberDescriptor.java:126)
[ERROR]         at ai.timefold.solver.quarkus.deployment.GizmoMemberAccessorEntityEnhancer.createMemberDescriptorForField(GizmoMemberAccessorEntityEnhancer.java:401)
[ERROR]         at ai.timefold.solver.quarkus.deployment.GizmoMemberAccessorEntityEnhancer.getGizmoSolutionOrEntityDescriptorForEntity(GizmoMemberAccessorEntityEnhancer.java:366)
[ERROR]         at ai.timefold.solver.quarkus.deployment.GizmoMemberAccessorEntityEnhancer.lambda$generateSolutionCloner$0(GizmoMemberAccessorEntityEnhancer.java:282)
[ERROR]         at io.quarkus.gizmo2.impl.GizmoImpl.lambda$class_$1(GizmoImpl.java:134)
[ERROR]         at io.smallrye.classfile.impl.ClassFileImpl.build(ClassFileImpl.java:144)
[ERROR]         at io.smallrye.classfile.ClassFile.build(ClassFile.java:558)
[ERROR]         at io.quarkus.gizmo2.impl.GizmoImpl.class_(GizmoImpl.java:131)
[ERROR]         at io.quarkus.gizmo2.Gizmo.class_(Gizmo.java:89)
[ERROR]         at ai.timefold.solver.quarkus.deployment.GizmoMemberAccessorEntityEnhancer.generateSolutionCloner(GizmoMemberAccessorEntityEnhancer.java:251)
[ERROR]         at ai.timefold.solver.quarkus.deployment.TimefoldProcessor.lambda$generateDomainAccessors$6(TimefoldProcessor.java:1092)
```

### PR DESCRIPTION
**Pull request by Christopher-Chianelli**
Fixes https://github.com/TimefoldAI/timefold-solver/issues/2165

### CODE REVIEW

File: core/src/main/java/ai/timefold/solver/core/config/util/ConfigUtils.java [hunk 1]
```diff
@@ -604,11 +604,31 @@ public static String addRandomSuffix(String name, RandomGenerator random) {
...
+    /**
+     * @param containingClass never null
+     * @param propertyName never null
+     * @return null if it doesn't exist
+     */
+    private static Method getSetterMethod(Class<?> containingClass, String propertyName) {
+        String setterName = ReflectionHelper.PROPERTY_MUTATOR_PREFIX + ReflectionHelper.capitalizePropertyName(propertyName);
+        Method[] methods = Arrays.stream(containingClass.getMethods())
+                .filter(method -> method.getName().equals(setterName))
+                .toArray(Method[]::new);
```
Comment (triceo) [inline core/src/main/java/ai/timefold/solver/core/config/util/ConfigUtils.java:616]: Does this actually fix the reported problem?

If I understand the report correctly, we have two setters with the same name, but different arguments. One of them is a correct setter, and the other is a perfectly valid overload.

This looks like it fails in that case. (Which it already did, that's why this was reported.)

Comment (Christopher-Chianelli) [reply core/src/main/java/ai/timefold/solver/core/config/util/ConfigUtils.java:616]: The correct method already exist; this was an incorrect one used in several places that exist only for config custom properties.

Comment (Christopher-Chianelli) [reply core/src/main/java/ai/timefold/solver/core/config/util/ConfigUtils.java:616]: (So I simply moved it to where it belongs, and made it private to prevent accident usage)

File: core/src/main/java/ai/timefold/solver/core/config/util/ConfigUtils.java [hunk 2]
```diff
@@ -604,11 +604,31 @@ public static String addRandomSuffix(String name, RandomGenerator random) {
...
+        if (methods.length == 0) {
+            return null;
+        }
+        if (methods.length > 1) {
+            throw new IllegalStateException("The containingClass (" + containingClass
```
Comment (triceo) [inline core/src/main/java/ai/timefold/solver/core/config/util/ConfigUtils.java]: Please replace the old way of doing exceptions.

**Review by triceo — APPROVED** [review]
LGTM once minor comment resolved.
