### PR TITLE
fix: unimproved terminations skip construction heuristic

### LINKED ISSUE #731: Unimproved termination should not terminate during CH
An unimproved termination should never active during a CH, because that's going to improve significantly when it finishes that CH phase anyway.

Note:
A CH could send a new best solution event every time one more extra planning variable is assigned.
It doesn't, because nobody needs that and it incurs a heavy performance cost due to solution cloning. Lets not change that.

### PR DESCRIPTION
**Pull request by triceo**
Closes #731 

The `Unimproved*` classes have the important changes.
The rest is just assorted cleanup while I was already in this ancient part of the codebase.

### CODE REVIEW

File: core/src/main/java/ai/timefold/solver/core/impl/phase/scope/AbstractPhaseScope.java [hunk 1]
```diff
@@ -29,14 +30,35 @@ public abstract class AbstractPhaseScope<Solution_> {
...
+    protected AbstractPhaseScope(SolverScope<Solution_> solverScope, boolean phaseSendsBestSolutionEvents) {
         this.solverScope = solverScope;
+        this.phaseSendsBestSolutionEvents = phaseSendsBestSolutionEvents;
     }
 
     public SolverScope<Solution_> getSolverScope() {
         return solverScope;
     }
 
+    public boolean phaseSendsBestSolutionEvents() {
```
Comment (zepfred) [inline core/src/main/java/ai/timefold/solver/core/impl/phase/scope/AbstractPhaseScope.java:58]: Should we use the default nomenclature `isPhaseSendsBestSolutionEvents`?

File: core/src/main/java/ai/timefold/solver/core/impl/solver/termination/BestScoreFeasibleTermination.java [hunk 2]
```diff
@@ -8,20 +8,19 @@
...
+        this.feasibleLevelsSize = scoreDefinition.getFeasibleLevelsSize();
         this.timeGradientWeightFeasibleNumbers = timeGradientWeightFeasibleNumbers;
-        if (timeGradientWeightFeasibleNumbers.length != feasibleLevelsSize - 1) {
+        if (timeGradientWeightFeasibleNumbers.length != this.feasibleLevelsSize - 1) {
             throw new IllegalStateException(
-                    "The timeGradientWeightNumbers (" + Arrays.toString(timeGradientWeightFeasibleNumbers)
-                            + ")'s length (" + timeGradientWeightFeasibleNumbers.length
-                            + ") is not 1 less than the feasibleLevelsSize (" + scoreDefinition.getFeasibleLevelsSize()
-                            + ").");
+                    "The timeGradientWeightNumbers (%s)'s length (%d) is not 1 less than the feasibleLevelsSize (%s)."
```
Comment (zepfred) [inline core/src/main/java/ai/timefold/solver/core/impl/solver/termination/BestScoreFeasibleTermination.java:21]:
```suggestion
The timeGradientWeightNumbers (%s)'s length (%d) is not 1 less than the feasibleLevelsSize (%d)
```

File: core/src/main/java/ai/timefold/solver/core/impl/solver/termination/UnimprovedTimeMillisSpentScoreDifferenceThresholdTermination.java [hunk 3]
```diff
@@ -127,18 +139,24 @@ protected boolean isTerminated(long safeTimeMillis) {
...
+            return 0.0;
+        }
         return calculateTimeGradient(phaseSafeTimeMillis);
     }
 
-    protected double calculateTimeGradient(long safeTimeMillis) {
-        long now = clock.millis();
-        long unimprovedTimeMillisSpent = now - (safeTimeMillis - unimprovedTimeMillisSpentLimit);
-        double timeGradient = unimprovedTimeMillisSpent / ((double) unimprovedTimeMillisSpentLimit);
+    private double calculateTimeGradient(long safeTimeMillis) {
```
Comment (zepfred) [inline core/src/main/java/ai/timefold/solver/core/impl/solver/termination/UnimprovedTimeMillisSpentScoreDifferenceThresholdTermination.java:156]:
```suggestion
    private double calculateTimeGradient(long safeTimeMillis) {
        if (!currentPhaseSendsBestSolutionEvents) {
            return 0.0;
        }
```

File: core/src/main/java/ai/timefold/solver/core/impl/solver/termination/UnimprovedTimeMillisSpentScoreDifferenceThresholdTermination.java [hunk 4]
```diff
@@ -127,18 +139,24 @@ protected boolean isTerminated(long safeTimeMillis) {
 
     @Override
     public double calculateSolverTimeGradient(SolverScope<Solution_> solverScope) {
+        if (!currentPhaseSendsBestSolutionEvents) {
```
Comment (zepfred) [inline core/src/main/java/ai/timefold/solver/core/impl/solver/termination/UnimprovedTimeMillisSpentScoreDifferenceThresholdTermination.java:142]:
```suggestion
```

File: core/src/main/java/ai/timefold/solver/core/impl/solver/termination/UnimprovedTimeMillisSpentScoreDifferenceThresholdTermination.java [hunk 5]
```diff
@@ -127,18 +139,24 @@ protected boolean isTerminated(long safeTimeMillis) {
...
+            return 0.0;
+        }
         return calculateTimeGradient(solverSafeTimeMillis);
     }
 
     @Override
     public double calculatePhaseTimeGradient(AbstractPhaseScope<Solution_> phaseScope) {
+        if (!currentPhaseSendsBestSolutionEvents) {
+            return 0.0;
+        }
```
Comment (zepfred) [inline core/src/main/java/ai/timefold/solver/core/impl/solver/termination/UnimprovedTimeMillisSpentScoreDifferenceThresholdTermination.java:152]:
```suggestion
```

File: core/src/main/java/ai/timefold/solver/core/impl/solver/termination/UnimprovedTimeMillisSpentScoreDifferenceThresholdTermination.java [hunk 6]
```diff
@@ -127,18 +139,24 @@ protected boolean isTerminated(long safeTimeMillis) {
 
     @Override
     public double calculateSolverTimeGradient(SolverScope<Solution_> solverScope) {
+        if (!currentPhaseSendsBestSolutionEvents) {
+            return 0.0;
```
Comment (zepfred) [inline core/src/main/java/ai/timefold/solver/core/impl/solver/termination/UnimprovedTimeMillisSpentScoreDifferenceThresholdTermination.java:143]:
```suggestion
```

File: core/src/main/java/ai/timefold/solver/core/impl/solver/termination/UnimprovedTimeMillisSpentScoreDifferenceThresholdTermination.java [hunk 7]
```diff
@@ -127,18 +139,24 @@ protected boolean isTerminated(long safeTimeMillis) {
...
+        }
```
Comment (zepfred) [inline core/src/main/java/ai/timefold/solver/core/impl/solver/termination/UnimprovedTimeMillisSpentScoreDifferenceThresholdTermination.java:144]:
```suggestion
```

File: core/src/main/java/ai/timefold/solver/core/impl/solver/termination/UnimprovedTimeMillisSpentTermination.java [hunk 8]
```diff
@@ -29,26 +31,50 @@ public long getUnimprovedTimeMillisSpentLimit() {
...
+        var bestSolutionTimeMillis = phaseScope.getPhaseBestSolutionTimeMillis();
         return isTerminated(bestSolutionTimeMillis);
     }
 
-    protected boolean isTerminated(long bestSolutionTimeMillis) {
-        long now = clock.millis();
-        long unimprovedTimeMillisSpent = now - bestSolutionTimeMillis;
-        return unimprovedTimeMillisSpent >= unimprovedTimeMillisSpentLimit;
+    private boolean isTerminated(long bestSolutionTimeMillis) {
+        return getUnimprovedTimeMillisSpent(bestSolutionTimeMillis) >= unimprovedTimeMillisSpentLimit;
```
Comment (zepfred) [inline core/src/main/java/ai/timefold/solver/core/impl/solver/termination/UnimprovedTimeMillisSpentTermination.java:72]:
```suggestion
        if (!currentPhaseSendsBestSolutionEvents) {
            return false;
        }
        return getUnimprovedTimeMillisSpent(bestSolutionTimeMillis) >= unimprovedTimeMillisSpentLimit;
```

File: core/src/main/java/ai/timefold/solver/core/impl/solver/termination/UnimprovedTimeMillisSpentTermination.java [hunk 9]
```diff
@@ -29,26 +31,50 @@ public long getUnimprovedTimeMillisSpentLimit() {
...
+        phaseStartedTimeMillis = clock.millis();
+    }
+
     // ************************************************************************
     // Terminated methods
     // ************************************************************************
 
     @Override
     public boolean isSolverTerminated(SolverScope<Solution_> solverScope) {
+        if (!currentPhaseSendsBestSolutionEvents) {
```
Comment (zepfred) [inline core/src/main/java/ai/timefold/solver/core/impl/solver/termination/UnimprovedTimeMillisSpentTermination.java:55]:
```suggestion
```

File: core/src/main/java/ai/timefold/solver/core/impl/solver/termination/UnimprovedTimeMillisSpentTermination.java [hunk 10]
```diff
@@ -29,26 +31,50 @@ public long getUnimprovedTimeMillisSpentLimit() {
...
+            return false;
```
Comment (zepfred) [inline core/src/main/java/ai/timefold/solver/core/impl/solver/termination/UnimprovedTimeMillisSpentTermination.java:56]:
```suggestion
```

File: core/src/main/java/ai/timefold/solver/core/impl/solver/termination/UnimprovedTimeMillisSpentTermination.java [hunk 11]
```diff
@@ -29,26 +31,50 @@ public long getUnimprovedTimeMillisSpentLimit() {
...
+        }
```
Comment (zepfred) [inline core/src/main/java/ai/timefold/solver/core/impl/solver/termination/UnimprovedTimeMillisSpentTermination.java:57]:
```suggestion
```

File: core/src/main/java/ai/timefold/solver/core/impl/solver/termination/UnimprovedTimeMillisSpentTermination.java [hunk 12]
```diff
@@ -29,26 +31,50 @@ public long getUnimprovedTimeMillisSpentLimit() {
...
         long bestSolutionTimeMillis = solverScope.getBestSolutionTimeMillis();
         return isTerminated(bestSolutionTimeMillis);
     }
 
     @Override
     public boolean isPhaseTerminated(AbstractPhaseScope<Solution_> phaseScope) {
-        long bestSolutionTimeMillis = phaseScope.getPhaseBestSolutionTimeMillis();
+        if (!currentPhaseSendsBestSolutionEvents) {
+            return false;
+        }
```
Comment (zepfred) [inline core/src/main/java/ai/timefold/solver/core/impl/solver/termination/UnimprovedTimeMillisSpentTermination.java:66]:
```suggestion
```

File: core/src/main/java/ai/timefold/solver/core/impl/solver/termination/UnimprovedTimeMillisSpentTermination.java [hunk 13]
```diff
@@ -29,26 +31,50 @@ public long getUnimprovedTimeMillisSpentLimit() {
...
         long bestSolutionTimeMillis = solverScope.getBestSolutionTimeMillis();
         return isTerminated(bestSolutionTimeMillis);
     }
 
     @Override
     public boolean isPhaseTerminated(AbstractPhaseScope<Solution_> phaseScope) {
-        long bestSolutionTimeMillis = phaseScope.getPhaseBestSolutionTimeMillis();
+        if (!currentPhaseSendsBestSolutionEvents) {
+            return false;
```
Comment (zepfred) [inline core/src/main/java/ai/timefold/solver/core/impl/solver/termination/UnimprovedTimeMillisSpentTermination.java:65]:
```suggestion
```

File: core/src/main/java/ai/timefold/solver/core/impl/solver/termination/UnimprovedTimeMillisSpentTermination.java [hunk 14]
```diff
@@ -29,26 +31,50 @@ public long getUnimprovedTimeMillisSpentLimit() {
...
+        }
         long bestSolutionTimeMillis = solverScope.getBestSolutionTimeMillis();
         return isTerminated(bestSolutionTimeMillis);
     }
 
     @Override
     public boolean isPhaseTerminated(AbstractPhaseScope<Solution_> phaseScope) {
-        long bestSolutionTimeMillis = phaseScope.getPhaseBestSolutionTimeMillis();
+        if (!currentPhaseSendsBestSolutionEvents) {
```
Comment (zepfred) [inline core/src/main/java/ai/timefold/solver/core/impl/solver/termination/UnimprovedTimeMillisSpentTermination.java:64]:
```suggestion
```

File: core/src/main/java/ai/timefold/solver/core/impl/solver/termination/UnimprovedTimeMillisSpentScoreDifferenceThresholdTermination.java [hunk 15]
```diff
@@ -104,20 +110,26 @@ public void stepEnded(AbstractStepScope<Solution_> stepScope) {
...
     }
 
-    protected boolean isTerminated(long safeTimeMillis) {
+    private boolean isTerminated(long safeTimeMillis) {
         // It's possible that there is already an improving move in the forager
         // that will end up pushing the safeTimeMillis further
         // but that doesn't change the fact that the best score didn't improve enough in the specified time interval.
         // It just looks weird because it terminates even though the final step is a high enough score improvement.
-        long now = clock.millis();
+        var now = clock.millis();
```
Comment (zepfred) [inline core/src/main/java/ai/timefold/solver/core/impl/solver/termination/UnimprovedTimeMillisSpentScoreDifferenceThresholdTermination.java:132]:
```suggestion
        if (!currentPhaseSendsBestSolutionEvents) {
            return false;
        }
        var now = clock.millis();
```

File: core/src/main/java/ai/timefold/solver/core/impl/solver/termination/UnimprovedTimeMillisSpentScoreDifferenceThresholdTermination.java [hunk 16]
```diff
@@ -104,20 +110,26 @@ public void stepEnded(AbstractStepScope<Solution_> stepScope) {
 
     @Override
     public boolean isSolverTerminated(SolverScope<Solution_> solverScope) {
+        if (!currentPhaseSendsBestSolutionEvents) {
```
Comment (zepfred) [inline core/src/main/java/ai/timefold/solver/core/impl/solver/termination/UnimprovedTimeMillisSpentScoreDifferenceThresholdTermination.java:113]:
```suggestion
```

File: core/src/main/java/ai/timefold/solver/core/impl/solver/termination/UnimprovedTimeMillisSpentScoreDifferenceThresholdTermination.java [hunk 17]
```diff
@@ -104,20 +110,26 @@ public void stepEnded(AbstractStepScope<Solution_> stepScope) {
...
+            return false;
```
Comment (zepfred) [inline core/src/main/java/ai/timefold/solver/core/impl/solver/termination/UnimprovedTimeMillisSpentScoreDifferenceThresholdTermination.java:114]:
```suggestion
```

File: core/src/main/java/ai/timefold/solver/core/impl/solver/termination/UnimprovedTimeMillisSpentScoreDifferenceThresholdTermination.java [hunk 18]
```diff
@@ -104,20 +110,26 @@ public void stepEnded(AbstractStepScope<Solution_> stepScope) {
...
+        }
```
Comment (zepfred) [inline core/src/main/java/ai/timefold/solver/core/impl/solver/termination/UnimprovedTimeMillisSpentScoreDifferenceThresholdTermination.java:115]:
```suggestion
```

File: core/src/main/java/ai/timefold/solver/core/impl/solver/termination/UnimprovedTimeMillisSpentScoreDifferenceThresholdTermination.java [hunk 19]
```diff
@@ -104,20 +110,26 @@ public void stepEnded(AbstractStepScope<Solution_> stepScope) {
...
         return isTerminated(solverSafeTimeMillis);
     }
 
     @Override
     public boolean isPhaseTerminated(AbstractPhaseScope<Solution_> phaseScope) {
+        if (!currentPhaseSendsBestSolutionEvents) {
```
Comment (zepfred) [inline core/src/main/java/ai/timefold/solver/core/impl/solver/termination/UnimprovedTimeMillisSpentScoreDifferenceThresholdTermination.java:121]:
```suggestion
```

File: core/src/main/java/ai/timefold/solver/core/impl/solver/termination/UnimprovedTimeMillisSpentScoreDifferenceThresholdTermination.java [hunk 20]
```diff
@@ -104,20 +110,26 @@ public void stepEnded(AbstractStepScope<Solution_> stepScope) {
...
+            return false;
```
Comment (zepfred) [inline core/src/main/java/ai/timefold/solver/core/impl/solver/termination/UnimprovedTimeMillisSpentScoreDifferenceThresholdTermination.java:122]:
```suggestion
```

File: core/src/main/java/ai/timefold/solver/core/impl/solver/termination/UnimprovedTimeMillisSpentScoreDifferenceThresholdTermination.java [hunk 21]
```diff
@@ -104,20 +110,26 @@ public void stepEnded(AbstractStepScope<Solution_> stepScope) {
...
+        }
```
Comment (zepfred) [inline core/src/main/java/ai/timefold/solver/core/impl/solver/termination/UnimprovedTimeMillisSpentScoreDifferenceThresholdTermination.java:123]:
```suggestion
```

File: core/src/test/java/ai/timefold/solver/core/impl/solver/termination/UnimprovedTimeMillisSpentScoreDifferenceThresholdTerminationTest.java [hunk 22]
```diff
@@ -130,13 +120,124 @@ void scoreImprovesTooLate_terminates() {
...
+
+        doReturn(START_TIME_MILLIS).when(clock).millis();
+        doReturn(0L).when(phaseScope).getStartingSystemTimeMillis();
+        doReturn(0L).when(solverScope).getBestSolutionTimeMillis();
+
+        termination.solvingStarted(solverScope);
+        termination.phaseStarted(phaseScope);
+        termination.stepEnded(stepScope);
+
+        // time has not yet run out
```
Comment (zepfred) [inline core/src/test/java/ai/timefold/solver/core/impl/solver/termination/UnimprovedTimeMillisSpentScoreDifferenceThresholdTerminationTest.java:153]: Let's also check the condition the time runs out

File: core/src/test/java/ai/timefold/solver/core/impl/solver/termination/UnimprovedTimeMillisSpentScoreDifferenceThresholdTerminationTest.java [hunk 23]
```diff
@@ -130,13 +120,124 @@ void scoreImprovesTooLate_terminates() {
...
```
Comment (zepfred) [inline core/src/test/java/ai/timefold/solver/core/impl/solver/termination/UnimprovedTimeMillisSpentScoreDifferenceThresholdTerminationTest.java:182]: Same as above

File: core/src/test/java/ai/timefold/solver/core/impl/solver/termination/UnimprovedTimeMillisSpentTerminationTest.java [hunk 24]
```diff
@@ -25,37 +28,107 @@ void forNegativeUnimprovedTimeMillis_exceptionIsThrown() {
...
 
-        when(clock.millis()).thenReturn(2000L);
-        when(phaseScope.getPhaseBestSolutionTimeMillis()).thenReturn(1000L);
+        doReturn(2000L).when(clock).millis();
+        doReturn(1000L).when(phaseScope).getPhaseBestSolutionTimeMillis();
         assertThat(termination.isPhaseTerminated(phaseScope)).isTrue();
         assertThat(termination.calculatePhaseTimeGradient(phaseScope)).isEqualTo(1.0, withPrecision(0.0));
     }
+
+    @Test
```
Comment (zepfred) [inline core/src/test/java/ai/timefold/solver/core/impl/solver/termination/UnimprovedTimeMillisSpentTerminationTest.java:71]: Nice tests!

File: docs/src/modules/ROOT/pages/optimization-algorithms/optimization-algorithms.adoc [hunk 25]
```diff
@@ -459,6 +459,13 @@ Just like <<timeMillisSpentTermination,time spent termination>>, combinations ar
 
 It is preffered to configure this termination on a specific `Phase` (such as ``<localSearch>``) instead of on the `Solver` itself.
 
+Several phases, such as construction heuristics, do not count towards this termination because
+they only trigger new best solution events when they are done.
+If such a phase is encountered, the termination is disabled and when the next phase is encountered,
```
Comment (zepfred) [inline docs/src/modules/ROOT/pages/optimization-algorithms/optimization-algorithms.adoc:464]:
```suggestion
If such a phase is encountered, the termination is disabled and when the next phase is started,
```

**Review by zepfred — APPROVED** [review]
LGTM! +1 after addressing some minor comments.
