### PR TITLE
fix: Make KOptListMoveSelector work when moveThreadCount != NONE

### LINKED ISSUE #250: MoveThreadCount + kOptListMoveSelector throws IndexOutOfBoundsException
Reproducible with the following solver configuration:
```
<?xml version="1.0" encoding="UTF-8"?>
<solver xmlns="https://timefold.ai/xsd/solver" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://timefold.ai/xsd/solver https://timefold.ai/xsd/solver/solver.xsd">
    <moveThreadCount>4</moveThreadCount>
    <constructionHeuristic/>
    <localSearch>
        <unionMoveSelector>
            <listChangeMoveSelector/>
            <listSwapMoveSelector/>
            <kOptListMoveSelector>
                <maximumK>3</maximumK>
            </kOptListMoveSelector>
        </unionMoveSelector>
    </localSearch>
</solver>
```

Not reproducible when using moveThreadCount = NONE.
Reproducible with moveThreadCount = 1.

Exception stacktrace:
```
13:31:20.654 ERROR [pool-9-thread-1] Solving with id (78fc989b-d863-4727-b509-62e33e5fe0b8) failed: message (The move thread with moveThreadIndex (0) has thrown an exception. Relayed here in the parent thread.): java.lang.IllegalStateException: The move thread with moveThreadIndex (0) has thrown an exception. Relayed here in the parent thread.
	at ai.timefold.solver.enterprise.core.multithreaded.OrderByMoveIndexBlockingQueue.take(OrderByMoveIndexBlockingQueue.java:111)
	at ai.timefold.solver.enterprise.core.multithreaded.MultiThreadedLocalSearchDecider.forageResult(MultiThreadedLocalSearchDecider.java:180)
	at ai.timefold.solver.enterprise.core.multithreaded.MultiThreadedLocalSearchDecider.decideNextStep(MultiThreadedLocalSearchDecider.java:144)
	at ai.timefold.solver.core.impl.localsearch.DefaultLocalSearchPhase.solve(DefaultLocalSearchPhase.java:72)
	at ai.timefold.solver.core.impl.solver.AbstractSolver.runPhases(AbstractSolver.java:83)
	at ai.timefold.solver.core.impl.solver.DefaultSolver.solve(DefaultSolver.java:193)
	at ai.timefold.solver.core.impl.solver.DefaultSolverJob.call(DefaultSolverJob.java:110)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IndexOutOfBoundsException: toIndex = 9
	at java.base/java.util.AbstractList.subListRangeCheck(AbstractList.java:507)
	at java.base/java.util.ArrayList.subList(ArrayList.java:1108)
	at ai.timefold.solver.core.impl.heuristic.selector.move.generic.list.kopt.MultipleDelegateList.subList(MultipleDelegateList.java:271)
	at ai.timefold.solver.core.impl.heuristic.selector.move.generic.list.kopt.MultipleDelegateList.moveElementsOfDelegates(MultipleDelegateList.java:86)
	at ai.timefold.solver.core.impl.heuristic.selector.move.generic.list.kopt.KOptListMove$UndoKOptListMove.doMoveOnGenuineVariables(KOptListMove.java:211)
	at ai.timefold.solver.core.impl.heuristic.move.AbstractMove.doMoveOnly(AbstractMove.java:26)
	at ai.timefold.solver.core.impl.score.director.AbstractScoreDirector.doAndProcessMove(AbstractScoreDirector.java:197)
	at ai.timefold.solver.enterprise.core.multithreaded.MoveThreadRunner.run(MoveThreadRunner.java:135)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	... 4 more
```

### PR DESCRIPTION
**Pull request by Christopher-Chianelli**
The issue came from the fact MultipleDelegateList returns a new instance of the rebased list on every call. This is problematic, since each FlipSublistAction expects rebase to return the same list across mulitple calls. When different instances are used, the FlipSublistAction modify different lists, causing the Undo move to be incorrect. (Since the list the FlipSublistAction operation on only has its flip incorporated in it instead of all flips). Since a new MultipleDelegateList is created for each move, we can safely store a cached result in one of its fields.

Fixes #250

### CODE REVIEW

File: core/core-impl/src/main/java/ai/timefold/solver/core/impl/heuristic/selector/move/generic/list/kopt/MultipleDelegateList.java [hunk 1]
```diff
@@ -42,6 +43,7 @@ public MultipleDelegateList(List<T>... delegates) {
         }
 
         this.totalSize = sizeSoFar;
+        this.cachedRebaseResult = null;
```
Comment (triceo) [inline core/core-impl/src/main/java/ai/timefold/solver/core/impl/heuristic/selector/move/generic/list/kopt/MultipleDelegateList.java:46]: Maybe add a comment here as to why it's safe to store this here?

**Review by triceo — APPROVED** [review]
Good to see the extra coverage.
One minor comment.

**Comment by Christopher-Chianelli** [comment]
There seem to be another issue that need to be patched (it fix one problem, but there appears to be another)

File: core/core-impl/src/main/java/ai/timefold/solver/core/impl/heuristic/selector/move/generic/list/kopt/MultipleDelegateList.java (hunk 1 above)
Comment (Christopher-Chianelli) [reply core/core-impl/src/main/java/ai/timefold/solver/core/impl/heuristic/selector/move/generic/list/kopt/MultipleDelegateList.java:46]: I think it not safe, due to the fact the accepted move is rebased twice (one for it score director, and one for the solver score director); I can move the cached result to KOptListMove

Comment (triceo) [reply core/core-impl/src/main/java/ai/timefold/solver/core/impl/heuristic/selector/move/generic/list/kopt/MultipleDelegateList.java:46]: Go for it. I think it makes more sense to store it there, because that is where `rebase` is.

**Comment by Christopher-Chianelli** [comment]
At this point, I think supplies/internals might be corrupted in multithreaded environment.

First, items in the list returned by SingletonInverseVariableSupply are different:
```
Before: 565809328:[TimeWindowedCustomer-39, TimeWindowedCustomer-72, TimeWindowedCustomer-44, TimeWindowedCustomer-38, TimeWindowedCustomer-86, TimeWindowedCustomer-84, TimeWindowedCustomer-42, TimeWindowedCustomer-92, TimeWindowedCustomer-98, TimeWindowedCustomer-61, *TimeWindowedCustomer-46, TimeWindowedCustomer-97, TimeWindowedCustomer-43, TimeWindowedCustomer-97, TimeWindowedCustomer-91, TimeWindowedCustomer-98, TimeWindowedCustomer-58*]
After: 565809328: [TimeWindowedCustomer-39, TimeWindowedCustomer-72, TimeWindowedCustomer-44, TimeWindowedCustomer-38, TimeWindowedCustomer-86, TimeWindowedCustomer-84, TimeWindowedCustomer-42, TimeWindowedCustomer-92, TimeWindowedCustomer-98, TimeWindowedCustomer-61, *TimeWindowedCustomer-85, TimeWindowedCustomer-97, TimeWindowedCustomer-43, TimeWindowedCustomer-100, TimeWindowedCustomer-91, TimeWindowedCustomer-93, TimeWindowedCustomer-58*]
```

Although it fairly deep: in one case, an item completely disappeared from existing (checked using my only InverseSupply):

```java
        findDelegate: for (int i = 0; i < delegates.length; i++) {
            List<T> delegate = delegates[i];
            if (delegate.isEmpty()) {
                out[i] = new ArrayList<>();
                continue;
            }
            EntityDescriptor<?> entityDescriptor = variableDescriptor.getEntityDescriptor();
            for (Object item : ((SolutionDescriptor<Object>) (entityDescriptor.getSolutionDescriptor()))
                    .getAllEntitiesAndProblemFacts(destinationScoreDirector.getWorkingSolution())) {
                if (entityDescriptor.getEntityClass().isAssignableFrom(item.getClass())) {
                    List<T> rebasedDelegate = (List<T>) variableDescriptor.getListVariable(item);
                    if (rebasedDelegate.contains(destinationScoreDirector.lookUpWorkingObject(delegate.get(0)))) {
                        out[i] = rebasedDelegate;
                        continue findDelegate;
                    }
                }
            }
           // this code was reached, which should never happen, considering it literally iterated through every entity and the solution is initialized.
            throw new IllegalArgumentException(
                    "Cannot find entity corresponding to " + destinationScoreDirector.lookUpWorkingObject(delegate.get(0)));
        }
```

**Comment by Christopher-Chianelli** [comment]
Confirmed it was the supplies. I managed to remove the supplies (by realizing I already have the original entities and can lookup list directly), and that fixed the code.

**Comment by Christopher-Chianelli** [comment]
Tested locally, new commit works on FULL_ASSERT multi-threaded vehicle routing with 3-opts

**Comment by triceo** [comment]
Thank you @Christopher-Chianelli, good job!
