### PR TITLE
fix: Do not set shadow variables to null when calculating from scratch in TRACED_FULL_ASSERT

### LINKED ISSUE #478: The same code get different exception betwee environmentMode TRACKED_FULL_ASSERT and FULL_ASSERT
**Describe the bug**
I have a project that uses the Chained Through Time pattern, when I debug it, an exception through from Timefold. But what makes me feel strange is that when I set different environmentMode values(TRACKED_FULL_ASSERT and FULL_ASSERT ), the different exception throws. So I don't know which is the actual exception.

**Expected behavior**
I expect FULL_ ASSERT and TRACKED_FULL_ASSERT will result in the same exception.

**Actual behavior**
environmentMode with FULL_ ASSERT and TRACKED_FULL_ASSERT resulted in different exceptions.

**To Reproduce**
When I set the environmentMode with FULL_ASSERT(SolverConfig.withEnvironmentMode(EnvironmentMode.FULL_ASSERT), or FAST_ASSERT, the exception is below.

```
java.lang.IllegalStateException: UndoMove corruption ([0/0/0/-22560/0/0/0/0/0/0]soft): the beforeMoveScore ([0/0/0/0]hard/[0/0/0/-775620/0/-8/-360/0/0/-3321]soft) is not the undoScore ([0/0/0/0]hard/[0/0/0/-798180/0/-8/-360/0/0/-3321]soft) which is the uncorruptedScore ([0/0/0/0]hard/[0/0/0/-798180/0/-8/-360/0/0/-3321]soft) of the workingSolution.

1) Enable EnvironmentMode TRACKED_FULL_ASSERT
(if you haven't already) to fail-faster in case there's a score corruption or variable listener corruption.
2) Check the Move.createUndoMove(...) method of the moveClass (ChainedSwapMove).
The move (PD04 {PD02} <-> PD02 {RES(D4-002)}) might have a corrupted undoMove (PD02 {RES(D4-002)} <-> PD04 {PD02}).
3) Check your custom VariableListeners (if you have any)
for shadow variables that are used by score constraints that could cause
the scoreDifference ([0/0/0/-22560/0/0/0/0/0/0]soft).

	at ai.timefold.solver.core.impl.score.director.AbstractScoreDirector.assertExpectedUndoMoveScore(AbstractScoreDirector.java:735)
	at ai.timefold.solver.core.impl.localsearch.decider.LocalSearchDecider.doMove(LocalSearchDecider.java:123)
	at ai.timefold.solver.core.impl.localsearch.decider.LocalSearchDecider.decideNextStep(LocalSearchDecider.java:97)
	at ai.timefold.solver.core.impl.localsearch.DefaultLocalSearchPhase.solve(DefaultLocalSearchPhase.java:72)
	at ai.timefold.solver.core.impl.solver.AbstractSolver.runPhases(AbstractSolver.java:82)
	at ai.timefold.solver.core.impl.solver.DefaultSolver.solve(DefaultSolver.java:193)
	at ai.timefold.solver.core.impl.solver.DefaultSolverJob.call(DefaultSolverJob.java:110)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

When I changed the environmentMode to TRACKED_FULL_ASSERT or NON_REPRODUCIBLE, then exception messages were below.

```
java.lang.IllegalStateException: The entity (PD01) has a variable (previousTaskOrResource) with value (PD03) which has a sourceVariableName variable (nextTask) with a value (null) which is not that entity.
Verify the consistency of your input problem for that sourceVariableName variable.
	at ai.timefold.solver.core.impl.domain.variable.inverserelation.SingletonInverseVariableListener.retract(SingletonInverseVariableListener.java:76)
	at ai.timefold.solver.core.impl.domain.variable.inverserelation.SingletonInverseVariableListener.beforeVariableChanged(SingletonInverseVariableListener.java:32)
	at ai.timefold.solver.core.impl.domain.variable.listener.support.VariableChangedNotification.triggerBefore(VariableChangedNotification.java:15)
	at ai.timefold.solver.core.impl.domain.variable.listener.support.VariableChangedNotification.triggerBefore(VariableChangedNotification.java:6)
	at ai.timefold.solver.core.impl.domain.variable.listener.support.AbstractNotifiable.triggerBefore(AbstractNotifiable.java:70)
	at ai.timefold.solver.core.impl.domain.variable.listener.support.VariableListenerNotifiable.notifyBefore(VariableListenerNotifiable.java:26)
	at ai.timefold.solver.core.impl.domain.variable.listener.support.VariableListenerSupport.beforeVariableChanged(VariableListenerSupport.java:161)
	at ai.timefold.solver.core.impl.domain.variable.listener.support.VariableListenerSupport.simulateGenuineVariableChange(VariableListenerSupport.java:262)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at ai.timefold.solver.core.impl.domain.solution.descriptor.SolutionDescriptor.lambda$visitAllEntities$8(SolutionDescriptor.java:910)
	at ai.timefold.solver.core.impl.domain.solution.descriptor.SolutionDescriptor.visitAllEntities(SolutionDescriptor.java:924)
	at ai.timefold.solver.core.impl.domain.solution.descriptor.SolutionDescriptor.visitAllEntities(SolutionDescriptor.java:910)
	at ai.timefold.solver.core.impl.domain.variable.listener.support.VariableListenerSupport.forceTriggerAllVariableListeners(VariableListenerSupport.java:235)
	at ai.timefold.solver.core.impl.domain.variable.listener.support.VariableListenerSupport.recalculateAllShadowVariablesFromScratch(VariableListenerSupport.java:245)
	at ai.timefold.solver.core.impl.score.director.AbstractScoreDirector.assertExpectedUndoMoveScore(AbstractScoreDirector.java:699)
	at ai.timefold.solver.core.impl.localsearch.decider.LocalSearchDecider.doMove(LocalSearchDecider.java:123)
	at ai.timefold.solver.core.impl.localsearch.decider.LocalSearchDecider.decideNextStep(LocalSearchDecider.java:97)
	at ai.timefold.solver.core.impl.localsearch.DefaultLocalSearchPhase.solve(DefaultLocalSearchPhase.java:72)
	at ai.timefold.solver.core.impl.solver.AbstractSolver.runPhases(AbstractSolver.java:82)
	at ai.timefold.solver.core.impl.solver.DefaultSolver.solve(DefaultSolver.java:193)
	at ai.timefold.solver.core.impl.solver.DefaultSolverJob.call(DefaultSolverJob.java:110)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

## Environment

**Timefold Solver Version or Git ref**: 1.5.0

**Output of `java -version`:** 17.0.5

**Output of `uname -a` or `ver`:**

## Additional information

Provide any and all other information which might be relevant to the issue.

### PR DESCRIPTION
**Pull request by Christopher-Chianelli**
Some variable listeners, such as CollectionInverseVariableListener, expect their shadow not to be null. The same can also be true for user's own variable listeners. Thus, we cannot set shadow variables to null and can only simulate changes to geninue variables in order to recalculate from scratch.

Fixes #478

### CODE REVIEW

File: core/core-impl/src/main/java/ai/timefold/solver/core/impl/score/director/AbstractScoreDirector.java [hunk 1]
```diff
@@ -695,14 +695,18 @@ public void assertExpectedUndoMoveScore(Move<Solution_> move, Score_ beforeMoveS
             assertShadowVariablesAreNotStale(undoScore, undoMoveText);
             String corruptionDiagnosis = "";
             if (trackingWorkingSolution) {
-                // Recalculate all shadow variables from scratch
-                variableListenerSupport.recalculateAllShadowVariablesFromScratch(workingSolution);
+                // Recalculate all shadow variables from scratch.
+                // We cannot set all shadow variables to null, since some variable listeners
+                // may expect them to be non-null.
+                //
```
Comment (triceo) [inline core/core-impl/src/main/java/ai/timefold/solver/core/impl/score/director/AbstractScoreDirector.java:701]:
```suggestion
```

File: core/core-impl/src/test/java/ai/timefold/solver/core/config/solver/EnvironmentModeTest.java [hunk 2]
```diff
@@ -142,28 +143,54 @@ void corruptedUndoShadowVariableListener(EnvironmentMode environmentMode) {
...
+                                new CorruptedUndoShadowSolution(List.of(e1, e2),
+                                        List.of(v1, v2))))
                         .withMessageContainingAll("corrupted undoMove",
                                 "Variables that are different between before and undo",
-                                "Actual value (v1) of variable valueClone on CorruptedUndoShadowEntity entity (CorruptedUndoShadowEntity) differs from expected (null)");
+                                "Actual value (v2) of variable valueClone on CorruptedUndoShadowEntity entity (CorruptedUndoShadowEntity) differs from expected (v1)");
             }
             case FULL_ASSERT,
                     FAST_ASSERT -> {
                 // FAST_ASSERT does not create snapshots since it does not intrusive, and hence it can only
```
Comment (triceo) [inline core/core-impl/src/test/java/ai/timefold/solver/core/config/solver/EnvironmentModeTest.java:176]:
```suggestion
                // FAST_ASSERT does not create snapshots since it is not intrusive, and hence it can only
```

**Review by triceo — APPROVED** [review]
